LIBS		:=
			
OPTIMIZATION	:= -O0
CFLAGS		+= -fpermissive -Wall #-DDEBUG_SRC_INFO
CFLAGS		+= $(OPTIMIZATION) $(INCLUDES)-fPIC -g -std=c++11
LDFLAGS		+= -shared 
CC		:= g++ 
#----------------------------------------------------------------------
INCLUDES	:= 	-I include \
			

#----------------------------------------------------------------------
OUT		:= 	./bin
#----------------------------------------------------------------------
#SRC_C		:=	
SRC_CPP		:=	./src/socket/ISocket.cpp \
			./src/socket/CSocketTCP.cpp \
			./src/socket/CSocketUDP.cpp \
			./src/socket/CSocketFactory.cpp
			
			
			
#----------------------------------------------------------------------
OBJ_C		+= $(SRC_C:%.c=%.o)
OBJ_CPP		+= $(SRC_CPP:%.cpp=%.o)
#OBJECTS  := $(SOURCES:$(SRCDIR)/%.c=$(OBJDIR)/%.o)
#----------------------------------------------------------------------
all: $(TARGET) clean
#----------------------------------------------------------------------
$(TARGET): $(OBJ_C) $(OBJ_CPP)
	@$(CC) -o $(TARGET)  $(OBJ_C) $(OBJ_CPP) $(LIBS) $(LDFLAGS)
	@mv $(TARGET) $(OUT)
	@echo "Installed => $(OUT)/"$@

$(OBJ_CPP): %.o : %.cpp
	@$(CC) $(CFLAGS) -c $< -o $@
	@echo "Compiled  => "$<
	
$(OBJ_C): %.o : %.c
	@$(CC) $(CFLAGS) -c $< -o $@
	@echo "Compiled  => "$<
#----------------------------------------------------------------------
clean:
	@rm -rf $(OBJ_C) $(OBJ_CPP) $(TARGET)
	@echo "Clean"
	